Creating Arrays from Python Lists


In [3]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)